sudo: required

language: ruby

services:
  - docker
before_install:
  - cd search_engine_ui
  - docker build -t rastamalik/crawler_ui .
  - docker run rastamalik/crawler_ui
  - docker ps -a
  

script:
  - bundle exec rake test  
