sudo: required

language: ruby
env:
  - DOCKER_COMPOSE_VERSION=1.4.2

services:
  - docker
before_install:
  - cd search_engine_ui
  - docker build -t rastamalik/crawler_ui .
  - docker run -d rastamalik/crawler_ui
  - cd ../search_engine_crawler
  - docker build -t rastamalik/crawler .
  - docker run -d rastamalik/crawler
  - docker ps -a
  


