Language: python
python:
- '2.7'
install:
- sudo pip install six --upgrade 
script:
- cd search_engine_ui/tests
- pip install -r requirements.txt -r requirements-test.txt
- coverage run -m unittest discover -s /
- coverage report --include app/ui.py

