Language: python
python:
- '2.7'
install:
- sudo pip install six --upgrade 
script:
- cd search_engine_ui/tests
- sudo pip install -r requirements-test.txt
- coverage run -m unittest discover -s /
- coverage report  app/ui.py

