Language: python
python:
- '2.7'
install:

- pip install backports.ssl_match_hostname

script:
- cd search_engine_ui/tests
- pip install -q -r requirements-test.txt
- coverage run -m unitest diccover -s /
- coverage report ui.py
