version: '3.3'
services:
  prometheus:
    image: rastamalik/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    networks:
      - reddit
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

  alertmanager: 
     image: rastamalik/alertmanager 
     command: 
      - '--config.file=/etc/alertmanager/config.yml' 
     ports: 
      - 9093:9093 
     networks:
      - reddit
  grafana:
    image: grafana/grafana:5.0.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    networks:
      - reddit  
    ports:
      - 3000:3000


 


volumes:
  prometheus_data:
  grafana_data:
networks:
   reddit:
